### ISSUE TITLE
how to take a thumbnail by gltf file?

### ISSUE THREAD

**Issue by sendreams** [javagl/JglTF#114]
i want to develop a function, user can upload gltf file, after uploading, the app take a thumbnail by gltf file.

**Comment by javagl** [comment]
The current functionality of JglTF does not include a proper renderer. There is the `jgtlf-viewer` project, but the functionality has never been updated from glTF 1.0 to glTF 2.0 to include a proper, full-fledged PBR renderer with IBL and such. While it would be cool to _have_ such a functionality in pure Java (and if it existed, then creating such a thumbnail would be trivial), the effort for _implementing_ a proper PBR renderer is too high for me to do this, for free, just so, in my spare time. Pull requests welcome.

The functionality that you are looking for can be achieved with Blender, by running it in "headless" mode. I do have a few lines of Blender (Python) code that actually _do_ generate screenshots/thumbnails, but there are many degrees of freedom for that.It's probably also possible to implement something like this with Three.js or BabylonJS, But I'm not aware of any existing tool for this.

**Comment by sendreams** [comment]
Thank you for your response. There are still too few tools for 3D rendering in the Java world. Unfortunately, we are a Chinese company and cannot afford to spend US dollars.

**Comment by javagl** [comment]
I'm not a company, but someone who did all this in his spare time. (And... as freelancer, I wouldn't mind being paid in ¥, but that's probably not the issue here)
