### ISSUE TITLE
Crash - Unhandled NullPointerException - findImageReader - guee MimeType

### ISSUE THREAD

**Issue by andresoviedo** [javagl/JglTF#120]
Dear friend

I am parsing a Gltf file and I found a bug in this line.  

If the ImageReader is not found, an unckeded NullPointerException is raised, therefore bubbling up in the call stack causing a crash.

https://github.com/javagl/JglTF/blob/609b7ce71c24d60e6a719ae65c6f4460083a66d6/jgltf-model/src/main/java/de/javagl/jgltf/model/image/ImageReaders.java#L70

Here is how to fix:

        if (imageReaders != null && imageReaders.hasNext())
        {
            ImageReader imageReader = imageReaders.next();
            imageReader.setInput(imageInputStream);
            return imageReader;
        }
        throw new IOException("Could not find ImageReader for image data");

Kind regards

**Comment by javagl** [comment]
The [documentation of `getImageReaders`](https://docs.oracle.com/javase/8/docs/api/javax/imageio/ImageIO.html#getImageReaders-java.lang.Object-) does not call out `null` as a possible return value. That alone may not be 100% reliable. But looking at the [`OpenJDK source code`](https://github.com/openjdk/jdk/blob/ab06a878f888827026424530781f0af414a8a611/src/java.desktop/share/classes/javax/imageio/ImageIO.java#L645), it looks like this cannot return `null`.

Which Java/JDK version are you using?
What kind of image data do you have there?

(An aside: One could probably think about different forms of error handling for "unknown" image data. I still have to think about WEBP and KTX support, for example. But I don't see where and how a `NullPointerException` should happen there...)

**Comment by andresoviedo** [comment]
Hello @javagl 
Thanks for the feedback
I am using android 12 - jdk 11
The image reader (at least) for . png images returns null

Once i fixes the Nullpointer, i got the expected checked IOException so program didnt crash. 

Regards

**Comment by javagl** [comment]
Yeah, I could have expected something Android-ish enwironment there (they sometimes differ from the JDK in details like this).


I still don't fully understand why (and under which conditions) `getImageReaders` should return `null`. When you mention an `IOException`: Does this happen when the PNG file is not found? Or does this happen when the PNG file is "invalid" in some way?

(I mean, `getImageReaders` will certainly _not_ return `null` for a simple, valid PNG file, would it?)

**Comment by andresoviedo** [comment]
Hello @javagl 

My bad. I found the actual issue:  In Android there is no javax.image API.  
Your API depends on that, so I mocked that. I forgot that I did that when doing my tests

For the sake of the record, I adapted your library to support Android as well
Thank you for the library and your prompt support

`           
           // java/de/javagl/jgltf/model/v2/GltfModelCreatorV2.java

           import android.graphics.BitmapFactory;
           import android.webkit.MimeTypeMap;

           private void initImageModels()
           {

            // android - detect quick
            String mimeType = imageModel.getMimeType();
            if (mimeType == null){
                String extension = MimeTypeMap.getFileExtensionFromUrl(imageModel.getUri());
                if (extension != null) {
                    mimeType = MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension);
                }
            }

            // android - decode quick
            if (mimeType == null){
                try (InputStream imageIS = Buffers.createByteBufferInputStream(imageModel.getImageData())){
                    BitmapFactory.Options opt = new BitmapFactory.Options();
                    opt.inJustDecodeBounds = true;
                    BitmapFactory.decodeStream(imageIS, null, opt);
                    mimeType = opt.outMimeType;
                } catch (Exception e) {
                    // ignore
                }
            }
`

**Comment by javagl** [comment]
I know that there are some classes (related to images) that are not available under Android. In fact, **this** was the reason for creating the [`model/image` package](https://github.com/javagl/JglTF/tree/master/jgltf-model/src/main/java/de/javagl/jgltf/model/image)! (Otherwise, all that could just be a `BufferedImage`). 

However, there might still be classes in the `model` package that use certain other classes that are _not_ available on Android - like some classes around `ImageIO`. The task to move these classes into a dedicated package is already on the radar. This might boil down to some `model/io/desktop` and `model/io/android` packages that are then used from `model`, using some sort of "plugin" mechanism.

In the broadest sense, this is tracked in https://github.com/javagl/JglTF/issues/117 (which already mentions the point about images), but I have not yet looked into the details.
