### ISSUE TITLE
Constants for buffer view target property

### ISSUE THREAD

**Issue by LocutusV0nB0rg** [javagl/JglTF#123]
I am using the DefaultBufferViewModel to create my GLTF structure. It however, requires the target property that describes the content type. The discussion in https://github.com/KhronosGroup/glTF/issues/1440 was useful to understand the purpose of this property, however, I now want to set these values. Of course I could just hardcode magic numbers or create my own constants for that purpose, but I feel, this should be part of JGLTF. However, when looking for anything similar to

```java
public static final int ARRAY_BUFFER = 34962;
public static final int ELEMENT_ARRAY_BUFFER = 34963;
```

I could find neither something similarly named, nor the number values used here. Am I missing something?

**Comment by LocutusV0nB0rg** [comment]
Very embarrassing: Looked in the wrong repository (jgltf vs. gltf).

The stuff is contained in the `GltfConstants` class.

**Comment by javagl** [comment]
Yeah, one could argue about the "best place" for storing such constants. The ones in `GltfConstants` only cover those that are necessary for glTF. But every library that has something to do with WebGL/OpenGL will have to define them _somewhere_ (and storing _all_ constants could be daunting). 

A while ago, I created https://javagl.github.io/GLConstantsTranslator/GLConstantsTranslator.html for that, and given that these constants are ... well, _constant_ and supposed to have the same value _everywhere_, even an inlined
```
final int GL_ARRAY_BUFFER = 34962
useThat(GL_ARRAY_BUFFER);
```
can be OK...
