### ISSUE TITLE
Building jgltf-browser on MacOS

### ISSUE THREAD

**Issue by javagl** [javagl/JglTF#2]
There has been a report about problems when building the jgltf-browser on MacOS in https://github.com/KhronosGroup/glTF/issues/685#issuecomment-242965935 

I just tried it again, with a fresh clone of the repository:

1. Create a directory for the test
2. Run `git clone https://github.com/javagl/JglTF.git` to create the clone
3. `cd JglTF`
4. `mvn clean install`
5. `cd jgltf-browser` (maybe you forgot this?)
6. `mvn clean compile assembly:single`

The result should be a file
`JglTF\jgltf-browser\target\jgltf-browser-0.0.0-SNAPSHOT-jar-with-dependencies.jar`
that can directly be executed.

---

The handling of native libraries is always difficult. For JOGL, the natives are automatically loaded from the JAR. For LWJGL, they usually have to handled manually. Therefore, I just created a new preview release that has been repackaged with [JarSplice](http://ninjacave.com/jarsplice), according to the recommendation for [Distributing Your LWJGL Application](http://wiki.lwjgl.org/wiki/Distributing_Your_LWJGL_Application) on the LWJGL wiki.

The new preview release can be downloaded here:
[https://github.com/javagl/JglTF/releases/tag/v0.0.0-alpha03](https://github.com/javagl/JglTF/releases/tag/v0.0.0-alpha03)

Hopefully, either the JOGL-based renderer or the LWJGL-based renderer will work. If there are problems or error messages, they can be reported here or in a dedicated issue.

**Comment by emadurandal** [comment]
Thank you for the issue!

I went through the steps. But failed again. 😢 
Here is the error log. I hope this will be of some help.
[build_error_log.txt](https://github.com/javagl/JglTF/files/442374/build_error_log.txt)

> The new preview release can be downloaded here:
> https://github.com/javagl/JglTF/releases/tag/v0.0.0-alpha03

Thank you! I appreciate it.
I will study from your refined products.

**Comment by javagl** [comment]
Thank you for this input. 

It does not really fail to *build* the library. It only fails on one of the "unit tests". It should be possible to compile it with

`mvn clean install -DskipTests=true`

---

Now, the question is: **Why** does this test fail? 

The test that fails is, admittedly, a *very* "pragmatic" and *very* ambituous one: It creates a "glTF-Embedded" representation of a glTF, writes this embedded glTF to a file, and then checks whether the resulting file is **bytewise identical** to a reference file. And this is not the case here:

> Difference in files ./src/test/resources/testModels/testBox/glTF-Embedded/Box.gltf and ./src/test/resources/testModels/testBox/output-glTF-to-glTF-Embedded/Box.gltf: array lengths differed, expected.length=6220 actual.length=6045

So there should be a file

`JglTF\jgltf-model\src\test\resources\testModels\testBox\output-glTF-to-glTF-Embedded\Box.gltf`

that only has 6045 bytes. It could be helpful if you added this file here as an attachment, so that I can have a look at it. 

I'm pretty sure that this is related to the Japanese Locale that I did not consider, and which may cause the file to be written with a different encoding or so. I'll likely have to revise this test, and see how it can be made more agnostic of the Locale...

**Comment by emadurandal** [comment]
Here you are. 
[Box.gltf.zip](https://github.com/javagl/JglTF/files/442556/Box.gltf.zip)

I tried terminal's locale as EN.

```
$ export LANG=C
```

But the result was same. maybe you have to try Japanese locale as OS level.
From now, I'll also try English locale as OS level in my mac.

**Comment by emadurandal** [comment]
I tried English locale as OS level setting on my Mac.
But the result was same.
I have no idea why. 😞

**Comment by emadurandal** [comment]
I tried `mvn clean install -DskipTests=true` too (in OS level English locale) .
But still failed. almost...

[build_error_log_2_skip_test.txt](https://github.com/javagl/JglTF/files/442621/build_error_log_2_skip_test.txt)

**Comment by javagl** [comment]
So there are two issues here:

The test failed because of the different line endings on Mac and Windows, `\r` vs. `\r\n`. (I expected it to be a minor thing, but still, the test is ambituous, because checking the identity of the file contents (even when ignoring the different line separators) might be a bit too strict). This should be fixed in https://github.com/javagl/JglTF/commit/8343657995e9afff2cc43eaed38474a80f202b78

The build process failed because the `maven-install-plugin` can't install during the build. The browser has 2 dependencies to JARs that are not in Maven Central, and I tried to install them from the local `/lib` directory into the local Maven Repo, but this cannot be done during the build. (It will check for these dependencies *before* installing them, so they are missing...). I now added them into a project-local Maven repo, in https://github.com/javagl/JglTF/commit/94b97a6c466833250216c8ab3e56c9a2f392ad29 - hope that works as expected. 

---

In the resulting JAR, the LWJGL renderer will still not work, because (as mentioned above), the native libraries still have to be added manually. I'll try to get rid of this as well, but ... 

...did you have a chance to try out the "v0.0.0-alpha03" release?

**Comment by emadurandal** [comment]
> ...did you have a chance to try out the "v0.0.0-alpha03" release?

I tried this release.
It works on my Windows PC (Windows 10, Quadro K2000D). But on my Mac (MacBook Pro Mid 2015, Radeon R9 M370X), It failed to show models. (Maybe OpenGL Initialization doesn't work properly?)

Anyway, I tried CeciumMan, and my `lady` model. It works perfectly!
(I know why there is some "twitching" of the lady because I keyed initial bind pose on zero frame on purpose.)

It seems to me that the JglTF's implementation of glTF skinning animation is the most accurate.

**Comment by javagl** [comment]
> Maybe OpenGL Initialization doesn't work properly?

Yes, it's always tricky: Native libraries, different GL versions and drivers, missing version specifiers in the glTF shader files... there are many possible sources of errors.

You might try switching between the "JOGL" renderer and the "LWJGL" renderer. When it *completely* fails to initialize the renderer, it should show an exception stack trace in the renderer window. But when there is another OpenGL error, it will not (yet) be displayed. When you start it from the console, with

    java -jar jgltf-browser-0.0.0-SNAPSHOT-jar-with-dependencies-repackaged.jar

it might show possible error messages in the console. (I'll try to show some Error-Dialog for these cases in the future)

---

> It seems to me that the JglTF's implementation of glTF skinning animation is the most accurate.

It's difficult to say this for sure - it might also be that my implementation is only "hiding" an error in the input, that shows up in the other viewers ;-) 

---

However, I assume that although there still are some issues on my todo-list, the basic problems of *this* issue (namely the failed unit test and the missing JARs during the build) are now resolved, and I'd close this issue soon then.
