### ISSUE TITLE
Is there still exist GltfDataReader in the new JglTF version?

### ISSUE THREAD

**Issue by Frank-Chan** [javagl/JglTF#26]
Hi,

Is there still exist GltfDataReader in the new [JglTF package](https://github.com/javagl/JglTF/releases/tag/v2.0.0-alpha01)? @javagl 

With the jgltf-model-0.0.0-SNAPSHOT.jar package I can use the code below to get and convert **glTF1.0** file to glb.
```java
    GltfDataReader r = new GltfDataReader();
    GltfData gltfData = r.readGltfData(gltfuri);
    gltfData = new GltfDataToBinaryConverter().convert(gltfData);
    BinaryGltfDataWriter w = new BinaryGltfDataWriter();
    w.writeBinaryGltfData(gltfData, glburi);
```
Recently, I want to use GltfDataReader to get **glTF2.0** file and convert it to glb. But in the new new [JglTF package](https://github.com/javagl/JglTF/releases/tag/v2.0.0-alpha01), I can't find _GltfDataReader, gltfData, GltfDataToBinaryConverter() and BinaryGltfDataWriter_.

Sincerely,
Frank-Chan

**Comment by Frank-Chan** [comment]
Dear @javagl ,
  Thanks for your timely feedback. It's a good idea to support both versions for  glTF 1.0 to glTF 2.0.  I tried both  GltfAsset  and GltfModel, however, the convert result of glTF2.0 to glb seems not properly, it can't display in the glb Viewers（[gltf-viewer](https://gltf-viewer.donmccurdy.com/)、[virtualgis](https://www.virtualgis.io/gltfviewer/)）.

Here is my convert result.
[gltf2glb.zip](https://github.com/javagl/JglTF/files/1906730/gltf2glb.zip)

   I would be greatly appreciated if you could spend some of your time check the problems for me.

Best regards

**Comment by javagl** [comment]
Throwing the original glTF it into the glTF-Validator at http://github.khronos.org/glTF-Validator/ reveals many errors, but they seem to fall into two categories:

                "code": "MESH_PRIMITIVE_INVALID_ATTRIBUTE",
                "message": "Invalid attribute name 'BINORMAL'.",
                "severity": 0,
                "pointer": "/meshes/0/primitives/45/attributes"

and

                "code": "MESH_PRIMITIVE_ATTRIBUTES_ACCESSOR_INVALID_FORMAT",
                "message": "Invalid accessor format '{VEC3, FLOAT}' for this attribute semantic. Must be one of ('{VEC4, FLOAT}').",
                "severity": 0,
                "pointer": "/meshes/0/primitives/59/attributes/TANGENT"

The first one should be covered by https://github.com/KhronosGroup/COLLADA2GLTF/issues/174 

The second one might be a bit more tricky. Depending on which version of COLLADA2GLTF you used, we might consider filing another bug report here.

--

In any case: I see that, for example, the glTF Viewer can render the original glTF nevertheless. 

But for the GLB, there seems to be another error, related to the GLB chunks. This is obviously an error in `jgltf-obj`. I'll investigate this.

**Comment by Frank-Chan** [comment]
I did run the program which you posted above.  The program which i used to convert the gltf file is below.

![20180426184322](https://user-images.githubusercontent.com/8639688/39301802-0cb45812-4983-11e8-8be4-a1d769fb0378.png)

**Comment by javagl** [comment]
Did it also *not* work for you with the code at https://github.com/javagl/JglTF/issues/26#issuecomment-380899842 ?

I tried the approach that you posted (BTW: http://idownvotedbecau.se/imageofcode ), and there indeed is some problem with the chunk size. 

I'll try to figure out what is wrong there and provide an update ASAP.

**Comment by Frank-Chan** [comment]
Thanks!

**Comment by javagl** [comment]
It's somehow important to know:

Did it work when you used the `GltfModelReader` and `GltfModelWriter`?

(If it worked, the issue that appeared with the `GltfAssetWriter` would have a lower priority...)

**Comment by Frank-Chan** [comment]
Yes, they can convert glTF to glb, but can't display in the glTF Viewer.

**Comment by javagl** [comment]
Using the model that you provided, it worked for me in the https://gltf-viewer.donmccurdy.com/ , at least. 

- Are there any error messages displayed in the console (F12) when you try to load the model?
- Can you provide the output of your conversion (i.e. the model that was created by the `GltfModelWriter`, and which does *not* work)? 

In any case, I'll try to investigate this further, and also try to fix the `GltfAssetWriter` issue.

**Comment by javagl** [comment]
The main point here is some sort of ambiguity in what exactly constitutes a "binary", "embedded" or "default" glTF model. 

The model in question contains images as embedded resources (i.e. using data URIs). When this is written as a binary glTF, then it is not clear how to decide whether these embedded resources should become part of the binary buffer, or whether they should remain embedded in the glTF asset. 

For now, the functionality of writing different model types is offered via the `GtlfModel` structures. When using

    gltfModelWriter.writeDefault(gltfModel, outputFile); // or
    gltfModelWriter.writeEmbedded(gltfModel, outputFile); // or
    gltfModelWriter.writeBinary(gltfModel, outputFile);

the resulting files will be "pure", meaning that they will either use external files for *all* resources, data URIs for *all* resources, or a binary blob for *all* resources. 

Compared to the `GtlfModel`, the `GltfAsset` is a "low-level" representation of the asset, which also allows for "mixed type" assets, and the corresponding writers will write the `GltfAsset` as-it-is, without converting the representation of the resources.

Nevertheless, the handling of "mixed type assets" contained some ambiguities that should largely be resolved via https://github.com/javagl/JglTF/commit/3eff0929085209ba90b69563f52f1f8de33019c0 

I'll close this one, and open a dedicated issue to track how the manual conversions should be handled.
