### ISSUE TITLE
How I can load OBJ in java to arrays? 

### ISSUE THREAD

**Issue by acterhd** [javagl/JglTF#3]
Hello. How I can load obj to SSBO buffers?

**Comment by javagl** [comment]
I have never worked with SSBOs. The site https://www.opengl.org/wiki/Shader_Storage_Buffer_Object suggests that this is a very new (OpenGL >= 4.3) feature, and from a first glance, I don't see how this relates to OBJ data. 

Can you elaborate the question, say what you are trying to accomplish, and in how far this is related to OBJ and/or (J)glTF?

**Comment by javagl** [comment]
@acterhd Assuming that this is not related to glTF or JglTF in particular, I'll close this. Drop me a note if you want it to be reopened.

**Comment by acterhd** [comment]
I just.... making path tracer, that may in future support gltf.

**Comment by javagl** [comment]
OK, if this is about https://github.com/acterhd/magnum-tracer, then I don't see how this is related to JglTF (the **J** stands for **Java**...). You can find links to tools at https://github.com/KhronosGroup/glTF , and for C++, I think that assimp is some sort of "de facto" standard library for Model I/O, and it is currently receiving glTF support - so this might be worth a try.

**Comment by acterhd** [comment]
Yes... early been in Java....
