### ISSUE TITLE
is extra field implemented in jgltf-model?

### ISSUE THREAD

**Issue by bkkite** [javagl/JglTF#32]
Hi, I need to use the 'extra' field in GlTFProperty.java but i don't see this field in GLTModel objects.

Could be the right way to access this field using  **_private final GlTF gltf_** object inside GltfModel?

**Comment by javagl** [comment]
The `extras` field is currently not routed through the model. So although accessing the `private GlTF` instance is **not** the "right" way to access it, it probably is the *only* way at the moment. In any case, the `*Model` interfaces are supposed to be a version-agnostic representation of a glTF asset. Accessing the underlying "raw" `GlTF` objects (in version 1.0 or 2.0) defeats this purpose.

I think this is in many ways similar to the `getName` method that was introduced in https://github.com/javagl/JglTF/commit/82bb96b0064732436fdc9e771bdbe717a2b8d8f2 .

So I think that it *could* be offered in a similar form, in an interface that all the `Model` interfaces extend. This interface would basically just correspond to the glTFProperty

Schema: https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/glTFProperty.schema.json
V1 result: https://github.com/javagl/JglTF/blob/master/jgltf-impl-v2/src/main/java/de/javagl/jgltf/impl/v2/GlTFProperty.java
V2 result: https://github.com/javagl/JglTF/blob/master/jgltf-impl-v1/src/main/java/de/javagl/jgltf/impl/v1/GlTFProperty.java

And thus, the `extras` could be offered from a basic interface. It could not be much more than a

    interface GltfProperty {
        Object getExtras();
    }

The application-specific nature of the `extras` data makes it necessary to provide access to it, in some form, while at the same time, it cannot be more specific than an `Object`, unfortunately...

**Comment by bkkite** [comment]
Understood!! Thank you.

**Comment by javagl** [comment]
Let's leave this open until it is implemented. (It's hard to give a schedule here, but to prevent it from getting lost too easily...)

**Comment by javagl** [comment]
The `extras` should now generally be passed through to the model via [`ModelElement#getExtras`](https://github.com/javagl/JglTF/blob/93697a0ca7593efd115126c8168688896aca4f27/jgltf-model/src/main/java/de/javagl/jgltf/model/ModelElement.java#L50), so I assume that it is OK to close this for now.
