### ISSUE TITLE
Could not open input stream for URI d maps\P_T_Parking.jpg

### ISSUE THREAD

**Issue by gisspace** [javagl/JglTF#36]
de.javagl.jgltf.model.io.UriResolvers$1 apply
Could not open input stream for URI d maps\P_T_Parking.jpg:  Invalid URI string: d maps\P_T_Parking.jpg

**Comment by javagl** [comment]
Having the actual glTF JSON could be helpful. But it seems like the URI contains an unescaped space: `d maps\P_T_Parking.jpg` (see https://www.w3schools.com/tags/ref_urlencode.asp).

So the first try would be to change the URI to `d%20maps\P_T_Parking.jpg`. 

(I'll have to investigate this further - depending on where the URL came from, I might have to do this encoding in JglTF)

**Comment by javagl** [comment]
Unless there are more details or a specific case to test this with, I'll close this for now.
