### ISSUE TITLE
does the validator support gltf v2?

### ISSUE THREAD

**Issue by jiangjiangcau** [javagl/JglTF#48]
From the code: https://github.com/javagl/JglTF/blob/master/jgltf-validator/src/main/java/de/javagl/jgltf/validator/Validator.java#L35
It seems it only support the validation for gltf v1. Do you have plan to extend it to support v2?

**Comment by javagl** [comment]
The validator was originally created for glTF 1.0, just to have a "first line of defense" for trying to load invalid glTF assets in the gltf-browser (i.e. to omit some checks, be able to make some assumptions, and gather information about why a certain asset could not be loaded). It had not been extended (and is essentially no longer used internally) after the transition to glTF 2.0. And you may also have seen the disclaimer: "This library is not intended for public use."

But if there is a demand: Creating a similar validator for glTF 2.0 should not be sooo hard (even though, of course, this would (at least initially) do **much** fewer checks than the [official glTF validator](https://github.khronos.org/glTF-Validator/) )

I'll try to allocate some time for that.

**Comment by javagl** [comment]
The validator that is implemented here is only used internally, and basically only in the ´jgltf-browser` (which hasn't been updated for ages). While I _might_ extend this in some way in the future, it is not something that I can address dedicatedly.

If someone wants to perform validation, this should be done with the official glTF-Validator from https://github.com/KhronosGroup/glTF-Validator
