### ISSUE TITLE
how to convert a  Gltf v1 to Gltf V2

### ISSUE THREAD

**Issue by D-WPanda** [javagl/JglTF#49]
how to convert a  Gltf v1 to Gltf V2？

**Comment by javagl** [comment]
This is not possible in the most generic sense: In glTF 1.0, you could have custom GLSL shader programs as part of the materials. In glTF 2.0, you have the PBR material representation. There is no way to translate a custom shader into a PBR model.

For nearly all other elements, the conversion from 1.0 to 2.0 would be simple (or even trivial), though. So depending on your goal, it could be possible to have a class that, for example, converts a glTF 1.0 model to a glTF 2.0, with a predefined set of default materials. 

(I locally already have some classes for such a conversion, but they would need to be polished a bit before they could be published sensibly).

**Comment by javagl** [comment]
It is possible to read glTF 1.0 data into a `GltfModel`. And it is possible to write a `GltfModel` as glTF 2.0. The only thing that is fundamentally incompatible is that of the `MaterialModel`. There are dedicated classes, `MaterialModelV1` and `MaterialModelV2`. In theory, some manual conversion could be implemented here. But it is not possible to do a complete, automated conversion of arbitrary material models. So this is not something that could sensibly be offered by JglTF. At least, not beyond some convenience functionality that could help for that. But this can be considered to be part of https://github.com/javagl/JglTF/issues/105
