### ISSUE TITLE
GlTF (v2) image data and GltfModel camera details (fov, aspect...)

### ISSUE THREAD

**Issue by enesaltinkaya** [javagl/JglTF#50]
Hi,

I am using Assimp with bindings provided by LWJGL to render a scene at the moment.
I want to switch to JglTF for model reading if i can manage.

I have a simple GLB file, exported from Blender, it has;
* a camera
* 2 lights 
* couple of boxes
* a material
* a texture with a small image

If i use **de.javagl.jgltf.impl.v2.GlTF** class;
* I can get the camera details like fov, aspect, near, far.
* But i cant get the image data that is embedded inside GLB file.

``` javascript
import de.javagl.jgltf.impl.v2.*;

public Test() throws Exception {
    FileInputStream fileInputStream = new FileInputStream("models/scene.glb");
    GltfAssetReader gltfAssetReader = new GltfAssetReader();
    GltfAsset gltfAsset = gltfAssetReader.readWithoutReferences(fileInputStream);
    GlTF gltf = (GlTF) gltfAsset.getGltf();

    for (Camera camera : gltf.getCameras()) {
        Float aspectRatio = camera.getPerspective().getAspectRatio();
        Float yfov = camera.getPerspective().getYfov();
        // i can get the camera details
    }
            
    for (Image image : gltf.getImages()) {
        Integer bufferViewIndex = image.getBufferView();
        BufferView bufferView = gltf.getBufferViews().get(bufferViewIndex);
        Integer bufferIndex = bufferView.getBuffer();
        Buffer buffer = gltf.getBuffers().get(bufferIndex);
        // cant reach the image data here
        // buffer.getImageData() ??
    }
}
```

If i use **de.javagl.jgltf.model.GltfModel** ;
* I cant get the camera details.
* But i can get the image data.

``` javascript
public Test() throws Exception {
    FileInputStream fileInputStream = new FileInputStream("models/scene.glb");
    GltfAssetReader gltfAssetReader = new GltfAssetReader();
    GltfAsset gltfAsset = gltfAssetReader.readWithoutReferences(fileInputStream);
    GltfModel gltfModel = GltfModels.create(gltfAsset);

    for (CameraModel cameraModel : gltfModel.getCameraModels()) {
        // cant get fov, aspect vs..
        // cameraModel.getPerspective() ??
    }

    for (ImageModel imageModel : gltfModel.getImageModels()) {
        ByteBuffer imageData = imageModel.getImageData();
        // i can get the image data
    }
}
```

Am i doing this wrong?
Or am i supposed to use both classes together?
Or is this not how this library supposed to be used?

Thanks for your hard work on this library, it is really neat.

**Comment by enesaltinkaya** [comment]
Forgot to mention;
I have add these maven dependency lines to my project.

```
<!-- https://mvnrepository.com/artifact/de.javagl/jgltf-model -->
<dependency>
    <groupId>de.javagl</groupId>
    <artifactId>jgltf-model</artifactId>
    <version>2.0.0</version>
</dependency>
```

**Comment by enesaltinkaya** [comment]
Turns out GLB file format is easy enough to parse.
So i implemented my own parser.

**Comment by javagl** [comment]
But just for completeness, referring to the point where you asked about the image data:

    for (Image image : gltf.getImages()) {
        Integer bufferViewIndex = image.getBufferView();
        BufferView bufferView = gltf.getBufferViews().get(bufferViewIndex);
        Integer bufferIndex = bufferView.getBuffer();
        Buffer buffer = gltf.getBuffers().get(bufferIndex);
        // cant reach the image data here
        // buffer.getImageData() ??
    }

The `de.javagl.jgltf.impl.v2` classes are the "low-level" representation of glTF, auto-generated from the schema. They provide the glTF as-it-is, in memory - basically a typed JSON representation, without any convenience functionality whatsoever. 

When you want to obtain the image data from this representation, you have to do everything manually. In your example, this would *roughly/untested* be something like this:

    Integer bufferViewIndex = image.getBufferView();
    BufferView bufferView = gltf.getBufferViews().get(bufferViewIndex);
    Integer bufferIndex = bufferView.getBuffer();
    Buffer buffer = gltf.getBuffers().get(bufferIndex);
    ByteBuffer imageData = 
            Buffers.createSlice(buffer, bufferView.getByteOffset(), bufferView.getByteLength());

So you have the `Buffer`, and take the "slice" of the `Buffer` that is described with the offset/length of the `BufferView`. 

This is exactly what the `...model` classes are doing. They serve as layer that is put on top of the low-level glTF 1.0 and glTF 2.0 representations, and offer such convenience functions.

---

The reason why the `CameraModel` does not offer things like the FOV is that you don't necessarily have a FOV. This is only the case when you have a *perspective* camera. But I agree that there should probably be a functionality to obtain the information. I opened https://github.com/javagl/JglTF/issues/51 (with some further details) to track this.
