### ISSUE TITLE
How to import this work in an Android Studio project ? 

### ISSUE THREAD

**Issue by agGitHub** [javagl/JglTF#53]
Hi,

I want to use this project :
https://github.com/oguzhancevik/obj2gltf

in my Android Project.

But, this obj2gltf project uses JglTF.

I don't manage to import JglTF in Android Studio without generating tons of errors.

How should I do to import JglTF in Android Studio ?

Thanks.

**Comment by javagl** [comment]
There have been some approaches for making this project "more compatible" with Android. There are some [issues related to Android](https://github.com/javagl/JglTF/search?q=android&type=issues), and these may lead to things like https://github.com/mikikg/AndroidJgltfViewer , but I don't know the lastest state of that.

More generally: I have to admit that I only did some _very_ basic experiments with Android until now. I actually got it running on my device at some point, but that has been quite a while ago. The versioning and general infrastructure of Android are not so trivial, and seem to change quickly. For example: Is it possible to use Java 8 features (like lambdas) in the meantime? Which "Android API level" should be targeted? ...

But more specifically: You mentioned that importing the project generated "tons of errors". Can you give some further information, about the API level that you used, or which _categories_ of errors you saw? (Not necessarily list all of them - I'm just wondering what changes might be necessary to avoid them).

I can also try to allocate some time for some Android experiments, but will have to set up the whole Android development toolchain first, so it's hard to give an exact timeline for that...

**Comment by javagl** [comment]
Trying to converge several Android-related issues into one, I opened https://github.com/javagl/JglTF/issues/117 to keep track of this.
