### ISSUE TITLE
Potential thread safety issue with V2 writeBinary

### ISSUE THREAD

**Issue by DanielOleo** [javagl/JglTF#61]
Hello,

We have a web service (spring boot) that produces GLB files on demand, recently it started to return "corrupted" files as more an more requests started to happen in parallel

The corruption seems inconsistent. But has some commonalities, the JSON and binary parts seems to be there and valid, but frequently the header would be wrong, or the BIN / JSON chunk type ASCII headers would be appear twice or missing entirely

Swapping to **writeEmbedded** resolved the issue immediately, and withstood an extreme load test I did (which **writeBinary** failed 1/100 files). So I'm assuming there's some issue buried within **writeBinary**

I haven't been able to track down the issue, but I thought I would raise the bug report either way incase your aware of something lurking in the code that might cause this

We are using 2.0.1 creating GLB v2 files

**Comment by DanielOleo** [comment]
Just to confirm it was `GltfModelWriter#writeBinary` that I was using.

The way I tested this ultimately is to write all the files out to a folder and then use `md5sum *` and that gave me a list of all the files and their hashes, I could quickly see from there if any of them deviated from the norm. Might be quicker for you to test that way also, rather than trying to read the files back in to validate them

My suspicions came down to the same area of code as yours but I'm a bit out of my depth in debugging this one

**Comment by javagl** [comment]
@DanielOleo I created a PR at https://github.com/javagl/JglTF/pull/62 , with a (slightly extended) test similar to the one that I sketched above. 

It's hard to _reliably_ reproduce thread-safety bugs and verify their fixes, so maybe you want to give it a try. (I'm reasonably sure that this indeed _was_ the reason for the problem, and the "pragmatic" test seems to confirm this, but regardless of that, the change would be an improvement that I'd merge at some point...)

**Comment by DanielOleo** [comment]
Yep I've run a few of my own tests and that does indeed seem to have solved the problem :)

**Comment by javagl** [comment]
There have been some other changes, and some small ones are still pending as of https://github.com/javagl/JglTF/issues/60 , so I haven't yet made up my mind about a schedule for a new (Maven) release. Is it workable for you to use the current repository state? (I'm juggling with priorities, and don't exactly know how "important" a new JglTF release is...)

**Comment by DanielOleo** [comment]
Yes we can continue to use the repo in the current state for now. Happy to wait a while if you have other things to consider
