### ISSUE TITLE
No way to get animation's ticksPerSecond

### ISSUE THREAD

**Issue by hYdos** [javagl/JglTF#84]

**Comment by javagl** [comment]
There is no concept of "ticks per second" in glTF. I explained that (using the term "frame rate") in [this comment in a related issue](https://github.com/javagl/JglTF/issues/82#issuecomment-1338321020).

Beyond that: The task to extend the animation handling to provide more (convenient) access to animations and animated data is already on the radar, for example, via the issue that I linked to. Feedback (in terms of actual _requirements_ and technical use-cases) is appreciated.
