### ISSUE TITLE
NodeModel Issues

### ISSUE THREAD

**Issue by hYdos** [javagl/JglTF#87]
For some reason, when using NodeModel it is not giving me a correct rotation. I have rotated my bone completely randomly and had no change in what im getting. This is how im reading rotation from a NodeModel.

    public static Matrix4fc convert(float[] translation, float[] rotation, float[] scale) {
        Matrix4f transformMatrix = new Matrix4f().identity();
        if (translation != null) transformMatrix.translate(translation[0], translation[1], translation[2]);
        if (rotation != null) transformMatrix.rotate(rotation[0], rotation[1], rotation[2], rotation[3]);
        if (scale != null) transformMatrix.scale(scale[0], scale[1], scale[2]);

        return transformMatrix;
    }

**Comment by hYdos** [comment]
Example of wrong values. I wrote a program to diff the expected result
![image](https://user-images.githubusercontent.com/25501603/224987146-68e3977c-35dc-4e5e-bc17-6a54339bcde2.png)
![image](https://user-images.githubusercontent.com/25501603/224987184-9e93ea5a-4bb7-43f0-bea0-6fd351798b0e.png)
few examples

**Comment by hYdos** [comment]
[pm0133.zip](https://github.com/javagl/JglTF/files/10967738/pm0133.zip)
model file im using

**Comment by javagl** [comment]
Hot candidates for errors like this are that the last component of the rotation quaternion sometimes has to be written at the first place, and that it often does not make much sense to try and extract Euler angles from a quaternion. 

But I don't know which Matrix library you are using (is it JOML? Apparently not...), or .... admittedly, in how far this question is related to the `NodeModel` in general....

**Comment by hYdos** [comment]
the format im writing to requires radian euler angles and to debug my incorrect results i have been converting euler angles to degrees to compare between the expected and actual value. Yes JOML is being used here.

**Comment by javagl** [comment]
When you are using JOML, then that call to `rotate` is the call to [`Matrix4f#rotate`](https://joml-ci.github.io/JOML/apidocs/org/joml/Matrix4f.html#rotate(float,float,float,float)):

> public Matrix4f rotate(float ang, float x, float y, float z)
> 
> Apply rotation to this matrix by rotating the given amount of radians about the specified (x, y, z) axis.

This expects an angle and an axis. The `rotation` values in glTF describe a *quaternion*. 

Try replacing the line
```
if (rotation != null) transformMatrix.rotate(rotation[0], rotation[1], rotation[2], rotation[3]);
```
with 
```
if (rotation != null) {
    Quaternionf q = new Quaternionf(rotation[0], rotation[1], rotation[2], rotation[3]);
    transformMatrix.rotate(q);
}
```
(Not tested, just guessing from the documentation - again, this "issue" is rather a question - and one that is fairly unrelated to JglTF or the `NodeModel`...)

**Comment by javagl** [comment]
I assume that this can be closed.
